name: Build and deploy

on:
  push:
    branches: ["main"]

env:
  APP_LOCATION: "dist"
  APP_ARTIFACT_LOCATION: "build"
  SWA_TOKEN: ${{ secrets.SWA_TOKEN }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: |
          npm install
          npm run build
        name: Build frontend artifact
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_app_build: true
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
